export const services = [
  {
    id: 'telegram',
    name: { ru: 'Telegram', en: 'Telegram' },
    icon: 'telegram',
    color: '#0088cc',
    popular: true,
    price: 0.5,
  },
  {
    id: 'whatsapp',
    name: { ru: 'WhatsApp', en: 'WhatsApp' },
    icon: 'whatsapp',
    color: '#25D366',
    popular: true,
    price: 0.8,
  },
  {
    id: 'google',
    name: { ru: 'Google', en: 'Google' },
    icon: 'google',
    color: '#4285F4',
    popular: true,
    price: 0.6,
  },
  {
    id: 'instagram',
    name: { ru: 'Instagram', en: 'Instagram' },
    icon: 'instagram',
    color: '#E4405F',
    popular: true,
    price: 0.7,
  },
  {
    id: 'facebook',
    name: { ru: 'Facebook', en: 'Facebook' },
    icon: 'facebook',
    color: '#1877F2',
    popular: true,
    price: 0.65,
  },
  {
    id: 'tiktok',
    name: { ru: 'TikTok', en: 'TikTok' },
    icon: 'tiktok',
    color: '#000000',
    popular: true,
    price: 0.75,
  },
  {
    id: 'twitter',
    name: { ru: 'Twitter / X', en: 'Twitter / X' },
    icon: 'twitter',
    color: '#1DA1F2',
    popular: false,
    price: 0.55,
  },
  {
    id: 'discord',
    name: { ru: 'Discord', en: 'Discord' },
    icon: 'discord',
    color: '#5865F2',
    popular: false,
    price: 0.45,
  },
  {
    id: 'microsoft',
    name: { ru: 'Microsoft', en: 'Microsoft' },
    icon: 'microsoft',
    color: '#00A4EF',
    popular: false,
    price: 0.6,
  },
  {
    id: 'amazon',
    name: { ru: 'Amazon', en: 'Amazon' },
    icon: 'amazon',
    color: '#FF9900',
    popular: false,
    price: 0.7,
  },
  {
    id: 'uber',
    name: { ru: 'Uber', en: 'Uber' },
    icon: 'uber',
    color: '#000000',
    popular: false,
    price: 0.8,
  },
  {
    id: 'airbnb',
    name: { ru: 'Airbnb', en: 'Airbnb' },
    icon: 'airbnb',
    color: '#FF5A5F',
    popular: false,
    price: 0.85,
  },
]

export const countries = [
  {
    id: 'russia',
    name: { ru: 'Россия', en: 'Russia' },
    code: 'RU',
    flag: '🇷🇺',
    numbersAvailable: 15000,
    priceFrom: 0.3,
  },
  {
    id: 'usa',
    name: { ru: 'США', en: 'USA' },
    code: 'US',
    flag: '🇺🇸',
    numbersAvailable: 12000,
    priceFrom: 0.5,
  },
  {
    id: 'uk',
    name: { ru: 'Великобритания', en: 'United Kingdom' },
    code: 'GB',
    flag: '🇬🇧',
    numbersAvailable: 8000,
    priceFrom: 0.6,
  },
  {
    id: 'germany',
    name: { ru: 'Германия', en: 'Germany' },
    code: 'DE',
    flag: '🇩🇪',
    numbersAvailable: 7500,
    priceFrom: 0.55,
  },
  {
    id: 'france',
    name: { ru: 'Франция', en: 'France' },
    code: 'FR',
    flag: '🇫🇷',
    numbersAvailable: 6000,
    priceFrom: 0.6,
  },
  {
    id: 'netherlands',
    name: { ru: 'Нидерланды', en: 'Netherlands' },
    code: 'NL',
    flag: '🇳🇱',
    numbersAvailable: 5500,
    priceFrom: 0.65,
  },
  {
    id: 'poland',
    name: { ru: 'Польша', en: 'Poland' },
    code: 'PL',
    flag: '🇵🇱',
    numbersAvailable: 4500,
    priceFrom: 0.4,
  },
  {
    id: 'ukraine',
    name: { ru: 'Украина', en: 'Ukraine' },
    code: 'UA',
    flag: '🇺🇦',
    numbersAvailable: 10000,
    priceFrom: 0.25,
  },
  {
    id: 'india',
    name: { ru: 'Индия', en: 'India' },
    code: 'IN',
    flag: '🇮🇳',
    numbersAvailable: 20000,
    priceFrom: 0.2,
  },
  {
    id: 'brazil',
    name: { ru: 'Бразилия', en: 'Brazil' },
    code: 'BR',
    flag: '🇧🇷',
    numbersAvailable: 8000,
    priceFrom: 0.45,
  },
  {
    id: 'indonesia',
    name: { ru: 'Индонезия', en: 'Indonesia' },
    code: 'ID',
    flag: '🇮🇩',
    numbersAvailable: 9000,
    priceFrom: 0.3,
  },
  {
    id: 'philippines',
    name: { ru: 'Филиппины', en: 'Philippines' },
    code: 'PH',
    flag: '🇵🇭',
    numbersAvailable: 7000,
    priceFrom: 0.35,
  },
]

export const getServiceById = (id: string) => services.find(s => s.id === id)
export const getCountryById = (id: string) => countries.find(c => c.id === id)
export const getPopularServices = () => services.filter(s => s.popular)
